### ISSUE TITLE
only gave 3 hour window today

### ISSUE THREAD

**Issue by janfrode** [kotope/ha_nordpool_cheapest_hours#1]
I'm using sensor.nordpool_kwh_krsand_nok_3_10_025, with numberOfSequentialHours = 8. Today it gave me the device start time 0:00 and device end time 3:00. That's not 8 hours..

**Comment by janfrode** [comment]
Sorry, I'm stoopid. I see now that I also need to change the calculation on line 67:

**Comment by kotope** [comment]
The "end time calculation" is on a different automation than the actual calculation and it does not have visibility to the other inside variable. This could be solved with external helper entity though.. maybe I'll change the automation to use it eventually :)
