### ISSUE TITLE
Variable number of sequential hours

### ISSUE THREAD

**Issue by KevinClocheret** [kotope/ha_nordpool_cheapest_hours#10]
How can we use a input_number to have a variable number of hours to be found.
I converted the input_number in a sensor and added it in the code but it is not working

`- name: "Cheapest hours energy (non-sequential)"
        unique_id: cheapest_hours_energy_non_sequential
        state: >
          {%- set sensor = (this.attributes.get('sensor', 'sensor.nordpool_kwh_be_eur_3_10_0') | string) -%}
          {{ state_attr(sensor, 'tomorrow_valid') }}
          {%- set numberOfHours = (this.attributes.get('number_of_hours', 'sensor.minimum_uren_verwarming') | int) -%}
        attributes:
          # CHANGE-ME: Set your personal configurations in here
          number_of_hours: sensor.minimum_uren_verwarming  # Amount of cheapest hours in search  {%- set numberOfHours = (this.attributes.get('number_of_hours',1) | int) -%}
          first_hour: 1 # Search starting hour
          last_hour: 23 # Search ending hour
          starting_today: true # Is the first_hour today (true / false). If false, first_hour needs to be before last_hour.
          sensor: sensor.nordpool_kwh_be_eur_3_10_0 # Nord pool sensor id. Check it ouf from your integrations page!
          fail_safe_starting: '00:00' # If nordpool fetch fails, starting time to make the calendar entry
          list: >-
            {%- set sensor = (this.attributes.get('sensor', 'sensor.nordpool_kwh_be_eur_3_10_0') | string) -%}
            {%- set numberOfHours = (this.attributes.get('number_of_hours', 'sensor.minimum_uren_verwarming') | int) -%}
            {%- set lastHour = (this.attributes.get('last_hour',23) | int) -%}
            {%- set firstHour = (this.attributes.get('first_hour', 0) | int) -%}
            {%- set startingToday = (this.attributes.get('starting_today', false) | bool) -%}
`

Also second question, what is decided as cheap??
I would like to find the lowest x hours regardless, so that won't be all valued as the 'cheapest'

Thx
Kevin

**Comment by boelle** [comment]
i can try and answer the last Q

you define x number of hours and it says when they start and end

these are my prices for tomorrow:

![image](https://github.com/kotope/ha_nordpool_cheapest_hours/assets/3832239/11e6ad4c-43a2-4e3c-84e7-f9b22ea0d8a4)


my drier needs 3 hours to dry clothes so the cheapest hours start 14:00 and ends 17:00
my heat pump can make a days worth of hot water in less than an hours so here it starts at 16:00 and ends at 17:00

maybe @kotope can confirm and answer the first Q

**Comment by kotope** [comment]
You can use variable on number of hours like this:

` number_of_hours: "{{ states.sensor.garage_heating_number_of_hours.state }}" # Amount of cheapest hours in search`

My 'garage_heating_number_of_hours' returns an int value that is then being used on the cheapest hours automation.
