### ISSUE TITLE
Configuration for the number of hours ignored in non-sequential version cheapest hours script

### ISSUE THREAD

**Issue by mtchetch** [kotope/ha_nordpool_cheapest_hours#11]
I have been searching for a working script that I can use to select an arbitrary number of expensive hours during each day (24h) period and use that to disable costly heating devices during that period. 

Your non-sequential version cheapest hours package looked very promising and i figured that it would do just that, but in an inverted way looking for cheapest hours. Thats fine since I can just invert what the device toggle does and make the output work as I wanted.

The issue is that the number of hours selected is inconsistent and does not respect the limits set. and I cannot get good results out of it.

So far I have tried out four different scripts from different authors that try to do the same thing but I have yet to get a single one of them to work in a reliable sane way. 

What I would like to accomplish:
- Trigger a bool sensor to turn off devices for X number of expensive hours in a given timeframe, usually 24h.
- Have the mechanism work reliably
- Have limits to handle a situation where the price is very flat. No need to turn anything off if the most expensive hours are 2 cents more expensive per kWh
- Have a way to visualize what is going to happen for the whole timeframe that nordpool data is availably (future)
- Have an easy way to change settings via helpers

My settings:

` 
# CHANGE-ME: Set your personal configurations in here
          number_of_hours: 20 # Amount of cheapest hours in search
          first_hour: 0 # Search starting hour
          last_hour: 23 # Search ending hour
          starting_today: true # Is the first_hour today (true / false). If false, first_hour needs to be before last_hour.
          sensor: sensor.nordpool_kwh_fi_eur_3_10_024 # Nord pool sensor id. Check it ouf from your integrations page!
`

`
 action:
    - if:
      - condition: template
        value_template: '{{ trigger.event == ''start'' }}'
      then:
      # CHANGE-ME: Actions to do when cheap hour starts
      - service: input_boolean.turn_off
        entity_id: input_boolean.expensive_energy
      else:
      # CHANGE-ME: Actions to do when cheap hour ends
      - service: input_boolean.turn_on
        entity_id: input_boolean.expensive_energy
    mode: single
`

With the configuration given I expect to get roughly 4 expensive hours per day and to be able to use that in my automations. This does not happen concistently and I have no idea why. The nordpool data is downloaded and the calendar markings do get created as well as the expensive_energy bool sensor gets updated.

All graphs are graphing the history of the sensors so no future data.

12h graph
![image](https://github.com/kotope/ha_nordpool_cheapest_hours/assets/11362763/432cbeba-2c99-4d8a-9824-3fc0790f32a8)

24h graph
![image](https://github.com/kotope/ha_nordpool_cheapest_hours/assets/11362763/7a4e68df-c566-4778-8d1e-bfb7c5006d31)

48h graph
![image](https://github.com/kotope/ha_nordpool_cheapest_hours/assets/11362763/6bc9cd2f-be92-4871-a9f6-58f7840c9fe9)

Calendar
![image](https://github.com/kotope/ha_nordpool_cheapest_hours/assets/11362763/fa2a2b73-25d5-46f9-ad62-bb66ebb3af3c)

Sensor logs

![image](https://github.com/kotope/ha_nordpool_cheapest_hours/assets/11362763/ef1bd256-bc93-4bd4-9e04-0e88686fe14b)

Please help.

**Comment by mtchetch** [comment]
The entire configuration for parts related to cheapest hours script:

![image](https://github.com/kotope/ha_nordpool_cheapest_hours/assets/11362763/61d5dd90-3751-467e-b921-ec2763c4a905)

/homeassistant/advanced_cheapest_hours_non_sequential.yaml

```
# This is the non-sequential version of cheapest hours automation using local calendar for time schedules
# Read more at https://www.creatingsmarthome.com/?p=2543
template:
  -  sensor:
      # The actual cheapest hour sensor. If multiple entries are required, copy, raname, set unique_id and configure attributes.
      - name: "Cheapest hours energy (non-sequential)"
        unique_id: cheapest_hours_energy_non_sequential
        state: >
          {%- set sensor = (this.attributes.get('sensor', 'sensor.nordpool_kwh_fi_eur_3_10_024') | string) -%}
          {{ state_attr(sensor, 'tomorrow_valid') }}
        attributes:
          # CHANGE-ME: Set your personal configurations in here
          number_of_hours: 20 # Amount of cheapest hours in search
          first_hour: 0 # Search starting hour
          last_hour: 23 # Search ending hour
          starting_today: true # Is the first_hour today (true / false). If false, first_hour needs to be before last_hour.
          sensor: sensor.nordpool_kwh_fi_eur_3_10_024 # Nord pool sensor id. Check it ouf from your integrations page!
          fail_safe_starting: '00:00' # If nordpool fetch fails, starting time to make the calendar entry
          list: >-
            {%- set sensor = (this.attributes.get('sensor', 'sensor.nordpool_kwh_fi_eur_3_10_024') | string) -%}
            {%- set numberOfHours = (this.attributes.get('number_of_hours',1) | int) -%}
            {%- set lastHour = (this.attributes.get('last_hour',23) | int) -%}
            {%- set firstHour = (this.attributes.get('first_hour', 0) | int) -%}
            {%- set startingToday = (this.attributes.get('starting_today', false) | bool) -%}
            {%- set ns = namespace(data=[], loopResult=[], res=[], loop=0) -%}
            {%- if state_attr(sensor, 'tomorrow_valid') == true -%}
              {%- if startingToday == true -%}{%- set ns.starting = firstHour -%}{%- else -%}{%- set ns.starting = firstHour + 24 -%}{%- endif -%}
              {%- set ns.ending = lastHour + 24 -%}

              {%- set arr = state_attr(sensor, 'today') + state_attr(sensor, 'tomorrow') -%}
              {%- for i in range(ns.starting, ns.ending) -%}
               {%- set start = (today_at("00:00") + timedelta( hours = i)) -%}
               {%- set end = (today_at("00:00") + timedelta( hours = i+1)) -%}
               {%- set ns.data = ns.data + [{
                 "start" : (start | as_timestamp | timestamp_local),
                 "end" : (end | as_timestamp | timestamp_local),
                 "price" : arr[i]}
               ] -%}
              {%- endfor -%}
              {%- set ns.data = (ns.data | sort(attribute='price'))[:numberOfHours] | sort(attribute='start') -%}
              {%- set ns.loopResult = ns.data -%}
              {% for i in range(0, 48) %}
                {%- set ns.loop = 0 -%}
                {%- for i in range(ns.loopResult| length) -%}
                  {% if i < ns.loop %}
                    {%- continue -%}
                  {% endif %}
                  {%- if ns.loop+1 < (ns.loopResult | length) -%}
                    {%- if ns.loopResult[ns.loop].end == ns.loopResult[ns.loop+1].start -%}
                      {%- set d = {'start': (ns.loopResult[ns.loop].start), 'end': (ns.loopResult[ns.loop+1].end) } -%}
                      {%- set ns.loop = ns.loop + 1 -%}
                      {%- set ns.res = ns.res + [d] -%}
                    {%- else -%}
                      {%- set d = {'start': (ns.loopResult[ns.loop].start), 'end': (ns.loopResult[ns.loop].end) } -%}
                      {%- set ns.res = ns.res + [d] -%}
                    {%- endif -%}
                  {%- else -%}
                    {%- set d = {'start': (ns.loopResult[ns.loop].start), 'end': (ns.loopResult[ns.loop].end) } -%}
                    {%- set ns.res = ns.res + [d] -%}
                  {%- endif -%}
                  {%- set ns.loop = ns.loop + 1 -%}
                {%- endfor -%}
                {%- if ns.loopResult | count == ns.res | count -%}
                  {%- break -%}
                {%- endif -%}
                {%- set ns.loopResult = ns.res -%}
                {%- set ns.res = [] -%}
                {%- set ns.loop = 0 -%}
              {% endfor %}
              {{ ns.loopResult }}
            {%- else -%}
              {{ [] }}
            {%- endif -%}
          failsafe: >-
            {%- set numberOfHours = (this.attributes.get('number_of_hours',1) | int) -%}
            {%- set start = (this.attributes.get('fail_safe_starting', '00:00') | string) -%}
            {%- set startTime = (today_at(start) + timedelta( hours = 24)) -%}
            {%- set endTime = (today_at(start) + timedelta( hours = 24 + numberOfHours)) -%}
            {%- set res =
              {'start': (startTime | as_timestamp | timestamp_local),
               'end': (endTime | as_timestamp | timestamp_local) }
            -%}
            [{{ res }}]

automation:
  - id: 'cheapest_hours_non_sequential_calendar_trigger'
    alias: 'Cheapest hours: Calendar trigger (non-sequential)'
    description: ''
    trigger:
    - platform: calendar
      event: start
      entity_id: calendar.electricity
    - platform: calendar
      event: end
      entity_id: calendar.electricity
    condition:
    - condition: template
      # CHANGE-ME: sensorId to used template
      value_template: >
        {%- set sensorId = 'sensor.cheapest_hours_energy_non_sequential' -%}
        {{ (state_attr(sensorId, 'friendly_name') | string) == trigger.calendar_event.summary }}
    action:
    - if:
      - condition: template
        value_template: '{{ trigger.event == ''start'' }}'
      then:
      # CHANGE-ME: Actions to do when cheap hour starts
      - service: input_boolean.turn_off
        entity_id: input_boolean.expensive_energy
      else:
      # CHANGE-ME: Actions to do when cheap hour ends
      - service: input_boolean.turn_on
        entity_id: input_boolean.expensive_energy
    mode: single

# Automation that triggers creating of the calendar entries
  - id: 'cheapest_hours_non_sequential_set_sequence'
    alias: 'Cheap hours: Set next non-sequantial chepeast hours'
    description: 'Checks tomorrow energy prices every hour and create calendar entry when available AND events not yet created'
    variables:
      # from which sensor we should try the tomorrow price validation
      # CHANGE-ME: sensorId to used template
      sensorId: >-
        {%- set sensorId = 'sensor.cheapest_hours_energy_non_sequential' -%}
        {{ sensorId }}
    trigger:
    - platform: time_pattern
      hours: /1
    condition:
    - condition: template
      value_template: >-
        {{ state_attr(state_attr(sensorId, 'sensor' ), 'tomorrow_valid') == true }}
    - condition: state
      entity_id: input_boolean.cheapest_hours_non_sequential_set
      state: 'off'
    action:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.cheapest_hours_non_sequential_set
    - service: script.cheapest_hours_create_multi_calendar
      data:
        sensorId: "{{ sensorId }}"
        attribute: "list"
        summary: "{{ (state_attr(sensorId, 'friendly_name') | string) }}"

  # Failsafe
  - id: 'cheapest_hours_non_sequential_failsafe'
    alias: 'Cheapest hours: Failsafe for non-sequential'
    description: 'Failsafe: Set cheapest hours from fail_safe value to amount of hours'
    variables:
      # from which sensor we should use for failsafe
      # CHANGE-ME: sensorId to used template
      sensorId: >-
        {%- set sensorId = 'sensor.cheapest_hours_energy_non_sequential' -%}
        {{ sensorId }}
    trigger:
    - platform: time
      at: '23:15'
    condition:
    - condition: state
      entity_id: input_boolean.cheapest_hours_non_sequential_set
      state: 'off'
    action:
    - service: input_boolean.turn_on
      data: {}
      target:
        entity_id: input_boolean.cheapest_hours_non_sequential_set
    - service: script.cheapest_hours_create_multi_calendar
      data:
        sensorId: "{{ sensorId }}"
        attribute: "failsafe"
        summary: "{{ (state_attr(sensorId, 'friendly_name') | string) }}"

# Clear calendar entry creation flag on new day
  - id: 'cheapest_hours_non_sequential_clear_set_flag'
    alias: 'Cheapest hours: Reset the set cheapest hours non-sequential helper for the next day'
    description: 'Clears cheapest hours helper boolean when the day changes.'
    trigger:
    - platform: time
      at: '01:15:00'
    condition: []
    action:
    - service: input_boolean.turn_off
      data: {}
      target:
        entity_id: input_boolean.cheapest_hours_non_sequential_set
    mode: single

# Helper to see if we've already created next day entries
input_boolean:
  cheapest_hours_non_sequential_set:
    name: Non-sequential cheapest hours set for the next day
    icon: mdi:clock

script:
# Script that creates the calendar entries from sensor
  cheapest_hours_create_multi_calendar:
    mode: parallel
    sequence:
      - repeat:
          count: "{{ state_attr(sensorId, attribute) | count }}"
          sequence:
            - service: calendar.create_event
              data:
                start_date_time: >
                  {{ state_attr(sensorId, attribute)[repeat.index-1].start | as_timestamp | timestamp_local }}
                end_date_time: >
                  {{ state_attr(sensorId, attribute)[repeat.index-1].end | as_timestamp | timestamp_local }}
                summary: >-
                  {{ summary }}
              target:
                entity_id: calendar.electricity
```

Home assistant automation setting:

![image](https://github.com/kotope/ha_nordpool_cheapest_hours/assets/11362763/5f3d8eb4-b819-4956-9360-29492d296564)

**Comment by kotope** [comment]
Ok, there's few issues in your configuration:
1. Your start hour is 00:00 starting today. However, nord pool prices are published in the after noon so you really can't have the time to start before that otherwise those calendar markings would be created on the past.
2. Your time frame is more than 24 hours. However, the time frame should be equal or less than 24 hours. Otherwise every day the prices are fetch the same timeframe would be calculated again and possibility of duplicate events exists.

**Comment by mtchetch** [comment]
> Ok, there's few issues in your configuration:
> 
>     1. Your start hour is 00:00 starting today. However, nord pool prices are published in the after noon so you really can't have the time to start before that otherwise those calendar markings would be created on the past.
> 
>     2. Your time frame is more than 24 hours. However, the time frame should be equal or less than 24 hours. Otherwise every day the prices are fetch the same timeframe would be calculated again and possibility of duplicate events exists.

Thanks for taking a look at the issue. Would it be possible to update the documentation on how the whole time-window system works and what to avoid.

I am trying to make the system work so that it would operate on a 24h timeframe and limit the amount of hours concidered expensive to a certain number. For example every 4 hours of a given 24h period would be marked as expensive and heating decisions could be made based on that.

What settings would you suggest to achieve this realiably?

**Comment by kotope** [comment]
Closing old issue, cause this repository is not in active development anymore.

I've created another better approach called AIO Energy Management that will handle the cheapest hours using an integration: https://github.com/kotope/aio_energy_management
