### ISSUE TITLE
Home assistant issue

### ISSUE THREAD

**Issue by gezuka77** [kotope/ha_nordpool_cheapest_hours#4]
Hi, 

I am getting the following warning in HA logs:

TemplateError('ValueError: Template error: float got invalid input 'unknown' when rendering template '{{ states('sensor.transmission_down_speed')|float * 1024 }}' but no default was specified') while processing template 'Template("{{ states('sensor.transmission_down_speed')|float * 1024 }}")' for attribute '_attr_native_value' in entity 'sensor.transmission_down_speed'
8:28:29 PM – (ERROR) helpers/template_entity.py - message first occurred at 8:28:29 PM and shows up 2 times
Error while processing template: Template("{{ states('sensor.transmission_down_speed')|float * 1024 }}")
8:28:29 PM – (ERROR) helpers/template.py - message first occurred at 8:28:29 PM and shows up 2 times
sensor.cheapest_hours_energy_tomorrow rendered invalid timestamp:
8:28:29 PM – (WARNING) Sensor

**Comment by kotope** [comment]
Closing old issue, cause this repository is not in active development anymore.

I've created another better approach called AIO Energy Management that will handle the cheapest hours using an integration: https://github.com/kotope/aio_energy_management
